### PR TITLE
Update faq.md

### PR DESCRIPTION
**Pull request by shawna-slh**

### CODE REVIEW

**Review by brewerj — CHANGES_REQUESTED** [review]
Thank you for starting this new question for the WCAG FAQ.

For the PR lines 198 - 200, I recommend making the question more explicit, and the answer less tentative, given that W3C's intentions on this have not changed. 

Proposed new question text: 

> Does W3C plan to send WCAG 2.1 or WCAG 2.2 to ISO for endorsement? 

Proposed new answer text: 

> W3C does not plan to send WCAG 2.1 to ISO for endorsement, and would not advise sending WCAG 2.1, given that WCAG 2.2 is expected to be finalized within 2022 and will represent an improvement in several respects. However, **W3C does expect to send WCAG 2.2 to ISO for endorsement**, and is currently formalizing plans to do so.

I believe that the gist of the proposed text above accurately reflects W3C's current plans, but realize that this may need editorial work.

**Comment by brewerj** [comment]
Shawn, my earlier comments above were accurate at the time, and would have been an improvement over existing language. But there have been additional developments on this since then, so at this point it is more accurate to change our response to the following: 

"**W3C does not plan to send WCAG 2.1** to ISO for endorsement and would not support that action, given that WCAG 2.2 is expected to be finalized within 2022 and will represent an improvement in several respects. 

**W3C expects to send WCAG 2.2 to ISO for endorsement**, and has started that process by notifying the ISO/IEC Joint Technical Committee 1 (JTC 1) of our intention to do so. "

From my perspective this is both ready and urgent to post. Please let me know of any questions or suggested revisions (for instance, for simplification). Thanks!

**Comment by shawna-slh** [comment]
NOTE: Edited directly in GitHub pages for quick update. Need to update the repo. Would like to suggest copyedits first.

**Comment by shawna-slh** [comment]
later updates done

**Pull request closed without merging**
