### PR TITLE
Update H1 - Title

### PR DESCRIPTION
**Pull request by bakkenb**
This is the first update

### CODE REVIEW

**Comment by yatil** [comment]
Not so sure we want to make that change :-D

**Comment by slhenry** [comment]
Actually, we want this page to be broader than 2.0 -- to cover 1.0 & 2.0 and future work... Let's talk if needed. :-)

**Comment by bakkenb** [comment]
I understand now. Thank you for the clarification.

**Comment by bakkenb** [comment]
Closing this change

**Pull request closed without merging**
