### PR TITLE
Bahasa Indonesia - WCAG 2 Overview

### PR DESCRIPTION
**Pull request by frirasyidi**
Add Bahasa Indonesia translation for:
- index
- docs
- glance
- non-web-ict
- wcag3-intro

Waiting for confirmation:
- commenting
- conformance
- faqs
- glance20
- new-in-21
- new-in-22
- translations
- wcag2a-conformance
- wcag2aa-conformance
- wcag2aaa-conformance

### CODE REVIEW

**Comment by remibetin** [comment]
Hi @frirasyidi,

I do not know if all subpages are ready for translation. For now, I can only confirm that index.md is ready for translation.
I will come back to you next week about the others.

**Comment by frirasyidi** [comment]
@remibetin ah, okay. I'll hold myself from doing the other pages. Thanks for notifying me.

Let me know if I can work on the other pages, otherwise the translation is ready for review.

**Comment by frirasyidi** [comment]
@shawna-slh, based on your list, I'll start translating the following pages:

- docs
- glance
- non-web-ict
- wcag3-intro

Also:

> - new-in-22 – This could use code clean up. Maybe postpone translating until that is done?

The new-in-22 is marked as go ahead to translate by @remibetin in here: https://github.com/w3c/wai-translations/issues/151. Should I postpone the translation?

As for the rest, I'll wait for the conclusion from your discussion on which are ready to be translated.

**Comment by shawna-slh** [comment]
> I'll start translating the following pages:

Thanks!

> The new-in-22 is marked as go ahead to translate by @remibetin in here: https://github.com/w3c/wai-translations/issues/151. Should I postpone the translation?

@remibetin and I will discuss this as soon as we get to it in our priority list. We'll get back to you asap.

**Comment by frirasyidi** [comment]
@shawna-slh @remibetin just wanted to confirm if the word "filer" on the second sentence from a paragraph in "docs.md" line 74 is a typo of "filter" or not. You can see the word is emboldened on the quote below:

> ﻿You can customize it so it shows what you are interested in at the time. There are "filters" for different roles, topics, and technologies (such as HTML, CSS, ARIA). And **filers** for [Level A, AA, or AAA success criteria](https://www.w3.org/WAI/WCAG21/Understanding/conformance#levels).

The paragraph refers to the capability of this resource to meet the user's needs: https://www.w3.org/WAI/WCAG22/quickref.

**Comment by remibetin** [comment]
@frirasyidi I am currently updating some of these resources. I will come back to you very soon. Feel free to ping me if you do not hear from me by Thursday 14 March.

**Comment by frirasyidi** [comment]
> @frirasyidi I am currently updating some of these resources. I will come back to you very soon. Feel free to ping me if you do not hear from me by Thursday 14 March.
> 
> Thanks for your contributions and your patience!

@remibetin wanted to follow up on this one. Any update?

**Comment by remibetin** [comment]
@frirasyidi 

Yes! Here is the status of each document:

## 👍 The document is ready and we welcome new translations
- index
- docs
- glance
- non-web-ict (low priority though)

## ⏳ Needs update before translation
- docs
- new-in-22
- new-in-21
- faqs
- wcag3-intro

## ❌  Do _not_ translate
- commenting
- conformance-logos
- glance20
- translations
- wcag2a-conformance
- wcag2aa-conformance
- wcag2aaa-conformance

Thanks again for your help and patience!

**Comment by remibetin** [comment]
> just wanted to confirm if the word "filer" on the second sentence from a paragraph in "docs.md" line 74 is a typo of "filter" or not. You can see the word is emboldened and italicized on the quote below:

@frirasyidi Indeed! I have fixed the typo in 96b4b45c3416961f2b4898d213616baa76a8de92

**Comment by frirasyidi** [comment]
@remibetin awesome, I'll find time to translate documents that are ready soon.

**Comment by remibetin** [comment]
@frirasyidi `wcag3-intro` has been updated today and is now ready for translation!

**Comment by remibetin** [comment]
Hi @frirasyidi,

The content of this repo has been moved to [wai-website repository](https://github.com/w3c/wai-website): I have therefore re-created your PR at https://github.com/w3c/wai-website/pull/825, and [added a comment](https://github.com/w3c/wai-website/pull/825#issuecomment-2298364791) for your consideration.

Thanks again for your contributions! Let me know how I can help you.

**Pull request closed without merging**
