### PR TITLE
Adding link to the editors draft.

### PR DESCRIPTION
**Pull request by alastc**
So new translators can avoid mistakes previous ones corrected...

### CODE REVIEW

**Comment by yatil** [comment]
@alastc Sorry, I missed that. I assigned @slhenry for review.

**Comment by yatil** [comment]
@slhenry Can we merge this pull request? I would do it, but I don’t “own” this page.

**Comment by nitedog** [comment]
I agree that this is not the place for it. Actually translators should refer to the errata document rather than the editor draft. Both the editor draft and the errata are linked from the spec document, so it is not a matter of adding this link on this page again, but rather providing good documentation for translators.

**Comment by alastc** [comment]
> Actually translators should refer to the errata document rather than the editor draft.

I kicked this off because I spoke to a translator who went to the WCAG21 page, created a load of issues, and then realised that most were already done in the editors draft.

As people go to the guidelines page and click on 'translations', which then brings them to this page, this is where the instructions for their next-step need to be clear. 

I don't mind what they are, but we do need to account for people's default behaviour.

**Comment by slhenry** [comment]
I added a heading:
> About Translating

and included "to ensure that you have the latest version, and to appropriately address pending updates and errata." to:
> **Note:** If you are interested in translating a specific document, make sure to announce it (as instructed in the links above) to facilitate collaboration, to avoid duplication of effort, to ensure that you have the latest version, and to appropriately address pending updates and errata.

**Pull request closed without merging**
